### ISSUE TITLE
When loading the block URL directly, it gives a 404

### ISSUE THREAD

**Issue by leoloso** [youknowriad/blockbook#10]
When clicking on any block, it refreshes the browser URL, such as https://youknowriad.github.io/blockbook/block/core---buttons. But then, refreshing on that page produces a 404

**Comment by youknowriad** [comment]
Looks like we need to add a 404.html to Github with the same content of index.html to do that. Thanks for catching that.

**Comment by tomjn** [comment]
Alternatively a `HashRouter` could be used in https://github.com/youknowriad/blockbook/blob/master/src/app/components/app/index.js
