### ISSUE TITLE
Blocks containing __ from wp.i18n cause blokbook to crash

### ISSUE THREAD

**Issue by fabiankaegy** [youknowriad/blockbook#19]
I tried importing a custom block into blockbook and it shows this error in the console: 

```error
TypeError: undefined is not an object (evaluating 'wp.i18n.__')
```

it was imported using the deconstruction syntax `const { __ } = wp.i18n;`

**Comment by youknowriad** [comment]
Thanks @fabiankaegy for the issue.

This is related to the first question on the FAQ https://github.com/youknowriad/blockbook#frequent-questions
you could solve it by building your blocks without relying on globals in the source but I'll add `wp.i18n` as a global to blockbook too to solve it.
